name: daily-build-workflow
on:
  schedule:
    # UTCで記述する事、この場合は日本時間 9 時にしたいので -9 して 0 にしてある
    - cron: "0 0 * * *"
    # 明示的な branch の指定はできず、デフォルト branch の latest commit に対して実行される
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

jobs:
  build_raspbian-buster_armv6:
    name: Build momo for raspbian-buster_armv6
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make raspbian-buster_armv6
        working-directory: build
        timeout-minutes: 120
  build_raspbian-buster_armv7:
    name: Build momo for raspbian-buster_armv7
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make raspbian-buster_armv7
        working-directory: build
        timeout-minutes: 120
  build_ubuntu-18_04_armv8_jetson_nano:
    name: Build momo for build_ubuntu-18.04_armv8_jetson_nano
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make ubuntu-18.04_armv8_jetson_nano
        working-directory: build
        timeout-minutes: 120
  build_macos:
    name: Build momo for macOS 10.15
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make macos
        working-directory: build
        timeout-minutes: 120
  build_ubuntu-18_04_x86_64:
    name: Build momo for build_ubuntu-18.04_x86_64
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make ubuntu-18.04_x86_64
        working-directory: build
        timeout-minutes: 120
  build_ubuntu-18_04_armv8:
    name: Build momo for build_ubuntu-18.04_armv8
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make ubuntu-18.04_armv8
        working-directory: build
        timeout-minutes: 120
  build_ubuntu-16_04_armv7_ros:
    name: Build momo for Ubuntu 16.04 armv7 ROS
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make ubuntu-16.04_armv7_ros
        working-directory: build
        timeout-minutes: 120
  build_ubuntu-16_04_x86_64_ros:
    name: Build momo for Ubuntu 16.04 x86_64 ROS
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - run: DOCKER_BUILDKIT=1 NOTTY=1 NOMOUNT=1 make ubuntu-16.04_x86_64_ros
        working-directory: build
        timeout-minutes: 120
